### ISSUE TITLE
ES5 to ESNext — here’s every feature added to JavaScript since 2015

### ISSUE THREAD

**Issue by sichenguo** [lightningminers/article#8]
* 原文链接：[Creating Good Roadmaps: 6 Practical Steps for Product Leaders](https://github.com/lightningminers/article/blob/master/TODO/ES5%20to%20ESNext%E2%80%8A%E2%80%94%E2%80%8Ahere%E2%80%99s%20every%20feature%20added%20to%20JavaScript%20since%202015.md)
* Markdown文件：[文件地址](https://github.com/xitu/gold-miner/blob/master/TODO1/creating-good-roadmaps-6-practical-steps-product-leaders.md)
* 文章分类：**前端**
* **注意：原文文件在 `TODO` 文件夹中**

**Comment by manooog** [comment]
* 具体分配
  * 因为 @wen  @菲 两位承担校对工作，每人400行
  * @诀钰 @Naruto 各 500行。然后剩下我来
  * 顺序： 暂定
    * @guokr       0 - 600
    * @菲            600 - 1000
    * @Naruto     1000 -1500
    * @诀钰         1500 - 2000
    * @wen          2000 --

**Comment by sichenguo** [comment]
|  id | 任务|
|--|--|
|gkr @sichenguo | 0-600| 
|菲 @chenmf6  | 600-1000|
|Naruto @Xixi20160512  | 1000 -1500| 
|诀钰 @hanxiansen | 1500 - 2000| 
|icepy @icepy | 2000 --| 

 诀钰 和icepy 两位大佬承担本次校对工作 🤙🏻🤙🏻🤙🏻
**deadline：**  2019-3-10 大家加油💪💪💪

**Comment by icepy** [comment]
本周周末开始校对。
